# Ejercicios de Numpy
Inteligencia Artificial - Facundo A. Lucianna - CEIA - FIUBA

A continuación veamos ejercicios de Numpy que deben resolver.

Ejercicio 1: Importa a Numpy como np

In [2]:
import numpy as np

Ejercicio 2: Crea un array de la siguiente lista

In [19]:
lista = [1, 2, 3, 4, 5]
np.array(lista)

array([1, 2, 3, 4, 5])

Ejercicio 3: Suma los siguientes dos arrays

In [20]:
a = np.array([[1,2,3],
              [4,5,6]])

b = np.array([[10,11,12],
              [13,14,15]])

a + b

array([[11, 13, 15],
       [17, 19, 21]])

Ejercicio 4: Multiplica por 3.2 al siguiente array (una matriz)

In [21]:
a = np.array([[4,2,2],
              [4,1,0]])
a * 3.2

array([[12.8,  6.4,  6.4],
       [12.8,  3.2,  0. ]])

Ejercicio 5: Convierta en una matriz cuadrada al siguiente array unidimensional.

1. Usando shape fijate que dimension tiene el array
2. Usando .reshape() convierta al array en una matriz cuadrada


In [22]:
a = np.array([x for x in range(9)])
a.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Ejercicio 6: Convierta el tipo del siguiente array en entero (int)

In [23]:
a = np.array([[2.5, 3.8, 1.5],
              [4.7, 2.9, 1.56]])

In [24]:
a.astype(np.int32)

array([[2, 3, 1],
       [4, 2, 1]], dtype=int32)

Ejercicio 7: Crea una matriz de identidad de orden 5 (usando np.eye) y luego transforma el tipo en booleano (bool)

In [25]:
a = np.eye(5)
a.astype(np.bool)

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False],
       [False, False, False,  True, False],
       [False, False, False, False,  True]])

Ejercicio 8: Cocatena de forma horizontal (una al costado de la otra) los siguientes arrays

In [26]:
a1 = np.array([[1,2,3],
               [4,5,6]])

a2 = np.array([[7,8,9],
               [10,11,12]])

In [27]:
np.concatenate([a1, a2], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

Ejercicio 9: Cocatena de forma vertical los mismos array

Ejercicio 9: Crea un array unidimensional que tenga los numeros de 0 a 100 (incluido) con saltos de 2.

In [28]:
np.arange(0,100,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

Ejercicio 10: Usando np.where() compara en que elementos el array **a** es mayor al array **b**

In [29]:
a = np.array([1,2,3,4,6])

b = np.array([1,3,2,4,5])

In [30]:
np.where(a<b, a, b)

array([1, 2, 2, 4, 5])

Ejercicio 11: Genera en un array una secuencia separada de forma equidistante de 5 numeros que van de 0 a 100 (inclusive ambos)

In [31]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

Ejercicio 12: Crea una matriz de 2x3 con todos los valores igual a 23 (Hint: podes usar [np.full](https://numpy.org/doc/stable/reference/generated/numpy.full.html) o [np.eye](https://numpy.org/devdocs/reference/generated/numpy.eye.html))


In [32]:
np.full((2,3), 23)

array([[23, 23, 23],
       [23, 23, 23]])

Ejercicio 13: Crea un array de 8x2 numeros aleatorios que sigan la distribucion normal (Hint: [np.random.normal](https://numpy.org/doc/stable/reference/random/generated/numpy.random.normal.html))

In [42]:
mu, sigma = 0, 0.1 # mean and standard deviation
np.random.normal(mu, sigma, (8,2))


array([[-0.01932864, -0.15837602],
       [ 0.06659877,  0.11128005],
       [ 0.02071824, -0.13629654],
       [-0.0362154 , -0.10050425],
       [-0.02303429,  0.01639078],
       [ 0.09566497, -0.00232664],
       [ 0.14484897,  0.0255079 ],
       [-0.05454964, -0.14682166]])

Ejercicio 14: Dadas las siguientes matrices, multipliquelas como matrices. Luego multipliquelas como si fueran arrays

In [44]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

b = np.array([[2,3,4],
              [5,6,7],
              [8,9,10]])

In [46]:
np.matmul(a,b)
a*b

array([[ 2,  6, 12],
       [20, 30, 42],
       [56, 72, 90]])

Ejercicio 15: Dado el siguiente array, ordenelo de forma ascendente (Hint: [np.argsort](https://numpy.org/doc/stable/reference/generated/numpy.argsort.html)). Luego de forma descendente.

In [3]:
a = np.array([1, 0, 82, 2, 939, 91, 1101, 199, 292, 2, 923, 387, 38, 299])
a

array([   1,    0,   82,    2,  939,   91, 1101,  199,  292,    2,  923,
        387,   38,  299])

In [6]:
ascending_indicides = np.argsort(a)

In [8]:
ascending_indicides[::-1]

array([ 6,  4, 10, 11, 13,  8,  7,  5,  2, 12,  9,  3,  0,  1])

----

Ejercicio 16: Lee el csv venta_libros en un array. Luego separa las columnas en 3 arrays diferentes, el primero llamado year, el segundo month, y el tercero books

In [19]:
arr = np.loadtxt("./datasets/venta_libros.csv", delimiter=",", dtype=np.int64, skiprows=1)
arr


array([[2019,    2,  400],
       [2019,    3,  339],
       [2019,    4,  389],
       [2019,    5,  141],
       [2019,    6,  332],
       [2019,    7,  386],
       [2019,    8,  307],
       [2019,    9,  304],
       [2019,   10,  167],
       [2019,   11,  133],
       [2019,   12,  151],
       [2020,    1,  276],
       [2020,    2,   57],
       [2020,    3,  125],
       [2020,    4,   27],
       [2020,    5,  222],
       [2020,    6,  363],
       [2020,    7,   26],
       [2020,    8,  162],
       [2020,    9,  383],
       [2020,   10,  383],
       [2020,   11,  179],
       [2020,   12,  386],
       [2021,    1,  432],
       [2021,    2,  482],
       [2021,    3,  202],
       [2021,    4,  115],
       [2021,    5,  420],
       [2021,    6,   87],
       [2021,    7,   36],
       [2021,    8,  489],
       [2021,    9,  440],
       [2021,   10,   83],
       [2021,   11,  258],
       [2021,   12,  281],
       [2022,    1,  393],
       [2022,    2,  227],
 

In [23]:
year=arr[:,0]
month=arr[:,1]
books=arr[:,2]
books

array([400, 339, 389, 141, 332, 386, 307, 304, 167, 133, 151, 276,  57,
       125,  27, 222, 363,  26, 162, 383, 383, 179, 386, 432, 482, 202,
       115, 420,  87,  36, 489, 440,  83, 258, 281, 393, 227, 236, 453,
       359, 252,  57, 473, 331, 349, 212, 131])

Usando np.max() obtenga el valor de ventas de libros más alto. Luego, busque a que mes y años corresponde

In [ ]:
max_ = np.max(books)
index= np.where(books == max_)
index = index[0][0]
month[index]

np.int64(2021)

In [ ]:

year[index]

Calcula las ventas totales, las ventas promedio, la mediana de las ventas y el desvio estandar (Hint: [np.sum](https://numpy.org/doc/stable/reference/generated/numpy.sum.html), [np.mean](https://numpy.org/doc/stable/reference/generated/numpy.mean.html), [np.median](https://numpy.org/doc/stable/reference/generated/numpy.median.html), [np.std](https://numpy.org/doc/stable/reference/generated/numpy.std.html))

In [32]:
np.sum(books)

np.int64(12436)

In [33]:
np.mean(books)

np.float64(264.59574468085106)

In [36]:
np.median(books)

np.float64(276.0)

In [37]:
np.std(books)

np.float64(136.14223781788837)